backend:
  name: git-gateway
  branch: master

media_folder: "static/img"
public_folder: "/img"

collections:
  - name: "pages"
    label: "Pages"
    files:
      - label: "Glossar"
        name: glossary
        file: "src/data/glossary/glossary.json"
        fields:
          - label: Titel
            name: title
            widget: text
          - label: Inhalt
            name: content
            widget: text
          - label: "Einträge"
            name: items
            widget: list
            fields:
              - label: Titel
                name: title
                widget: text
              - label: Inhalt
                name: content
                widget: text
              - label: Sektionen
                name: sections
                widget: list
                fields:
                  - label: Titel
                    name: subtitle
                    widget: text
                  - label: Inhalt
                    name: content
                    widget: text
  - name: "universities"
    label: "Hochschule"
    folder: "src/data/schools"
    extension: json
    create: true
    slug: "{{university}}-{{slug}}"
    identifier_field: name
    summary: "{{city}} - {{name}}"
    fields:
      - {label: Name, name: name, widget: string}
      - {label: Stadt, name: city, widget: string}
      - {label: Adresse, name: address, widget: string}
      - label: Hochschultyp
        name: type
        widget: "select"
        options:
          - { label: "Universität", value: "university" }
          - { label: "Kunsthochschule", value: "artCollege" }
          - { label: "Fachhochschule", value: "college" }
      - {label: Longitude, name: longitude, widget: number, valueType: float}
      - {label: Latitude, name: latitude, widget: number, valueType: float}
  - name: "master"
    identifier_field: name
    label: "Master"
    folder: "src/data/masters"
    extension: json
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    summary: "{{universityName}} - {{name}}"
    fields:
      - {label: Studiengang, name: name, widget: string}
      - label: "Hochschule"
        name: "universityName"
        widget: "relation"
        collection: "universities"
        searchFields: ["name", "city"]
        valueField: "name"
        displayFields: ["name", "city"]
      - label: "Hochschule Details"
        name: "universityDetails"
        widget: object
        fields:
        - label: "Hochschulübergreifend"
          name: otherUniversity
          widget: text
          default: "nein"
        - label: "Fachbereich"
          name: department
          widget: text
          default: ""
      - label: Ausrichtung
        name: direction
        widget: object
        fields:
          - label: Abschluss
            name: degree
            default: "ma"
            widget: select
            options:
              - {label: "Master of Arts (MA)", value: ma}
              - {label: "Master of Fine Arts (MFA)", value: mfa}
              - {label: "Master of Science (MSc)", value: msc}
          - label: Ausrichtung
            name: direction
            widget: select
            multiple: true
            default: []
            options:
              - {label: Praktisch, value: practical}
              - {label: Theoretisch, value: theoretical}
          - label: Mastertyp
            name: masterType
            widget: select
            default: "consecutive"
            options:
              - {label: Konsekutiv, value: consecutive}
              - {label: "Nicht-konsekutiv", value: notConsecutive}
              - {label: "Weiterbildend", value: studyingFurther}
      - label: "Inhaltlichel Fokus und fachliche Zusammensetzung"
        name: "topicAndFocus"
        widget: object
        fields:
          - label: "Inhaltlicher Fokus"
            widget: select
            name: topicFocus
            default: "fachspezifisch"
            options:
              - {label: Fachspezifisch, value: fachspezifisch}
              - {label: Fachübergreifend, value: fachuebergreifend}
              - {label: Thematisch, value: thematisch}
          - label: "Disziplinäre Zusammensetzung"
            name: functionalComposition
            widget: select
            default: "artAndNonArt"
            options:
              - {label: "Disziplinär", value: "disciplinary"}
              - {label: "Interdisziplinär gestalterisch", value: "interdisciplinaryArt"}
              - {label: "Gestalterisch & Nicht-gestalterisch", value: "artAndNonArt"}
          - label: "Zugelassene Disziplinen"
            name: allowedDisciplines
            widget: string
            default: ""
          - label: "Zugelassene Disziplinen Tags"
            name: allowedDisciplinesTag
            widget: select
            multiple: true
            default: []
            options:
              - {label: "Digitale Medien", value: "digital"}
              - {label: "Film/Fotografie", value: "filmAndPhotograpy"}
              - {label: "Illustrationen", value: "illustrations"}
              - {label: "Mode/Textil", value: "fashion"}
              - {label: "Produkt/Industrie", value: "product"}
              - {label: "Innenarchitektur", value: room}
              - {label: "Schmuck", value: jewelry}
              - {label: "Visuelle Kommunikation", value: "visualCommunication"}
      - label: "Zeit und Geld"
        name: timeAndMoney
        widget: object
        fields:
          - label: Bewerbungsfristen
            name: applicationDeadlines
            widget: list
            fields:
              - label: Zulassungssemester
                name: type
                widget: "select"
                options:
                  - { label: "Sommersemester", value: "summer" }
                  - { label: "Wintersemester", value: "winter" }
              - {label: Datum, name: date, widget: date, dateFormat: "DD.MM.YYYY"}
              - {label: International, name: international, widget: boolean, default: false}
          - label: Studienformen
            name: allowedForms
            widget: select
            multiple: true
            default: []
            options:
            - {label: Vollzeit, value: fullTime}
            - {label: Teilzeit, value: partTime}
            - {label: Berufsbegleitend, value: extraOccupational}
            - {label: Ferstudium, value: remote}
          - label: Gebühren
            name: costs
            widget: number
            valueType: int
            default: 0
          - label: Regelstudienzeit (Semester)
            name: semester
            widget: number
            valueType: int
            default: 4
      - label: Internationalität
        name: internationality
        widget: object
        fields:
          - label: Hauptunterrichtssprache
            name: mainLanguages
            widget: select
            multiple: true
            default: ["german"]
            options:
              - {label: deutsch, value: german}
              - {label: english, value: english}
          - label: "Integriertes Auslandssemester"
            name: semesterAbroad
            widget: select
            options:
              - {label: "Ja", value: "yes"}
              - {label: "Nein", value: "no"}
              - {label: "Wahlweise", value: "choose"}
          - label: "Doppelabschluss"
            name: "doubleDegree"
            widget: boolean
            default: false
      - label: Metadata
        name: metadata
        widget: object
        fields:
        - {label: Website, name: website, widget: string}
        - {label: Facebook, name: facebook, widget: string}
        - {label: Instagram, name: instagram, widget: string}
        - {label: Twitter, name: twitter, widget: string}

